# Generated by Django 4.1.7 on 2023-03-14 21:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_management_lecturers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='management',
            name='lecturers',
        ),
    ]
