# Generated by Django 4.1.7 on 2023-03-16 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_remove_management_lecturers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='management',
            name='date_of_employment',
            field=models.DateField(max_length=20, null=True),
        ),
    ]
